module

public import Carleson.Classical.ClassicalCarleson
public import Carleson.MetricCarleson.Main

/-!
# Solution file for Carleson's theorem and the metric space Carleson theorems

This is the Solution file for the Carleson formalization project
<https://github.com/fpvandoorn/carleson>. `PalomarChallenge.lean` states three theorems, and this
file proves them using the rest of the project.

The definitions used in `PalomarChallenge.lean` (`partialFourierSum`, `KernelProofData`,
`IsCancellative`, `carlesonOperator`, ...) are verbatim copies of the definitions in
`Carleson/Defs.lean`. This file gets those definitions by importing the project (which imports
`Carleson.Defs`), so the statements below are the same terms as in the Challenge. Each theorem
follows directly from the corresponding theorem of the project:

* `classical_carleson_theorem` is `classical_carleson`
  (`Carleson/Classical/ClassicalCarleson.lean`), Theorem 1.0.1 of the blueprint.
* `metric_space_carleson` is `metric_carleson` (`Carleson/MetricCarleson/Main.lean`),
  Theorem 1.1.1 of the blueprint.
* `linearized_metric_space_carleson` is `linearized_metric_carleson`
  (`Carleson/MetricCarleson/Linearized.lean`), Theorem 1.1.2 of the blueprint.

The only step that is not a direct application is the constant. The project states Theorems
1.1.1 and 1.1.2 with the constant
`C1_0_2 a q = 2 ^ ((3 * 𝕔 + 18 + 5 * (𝕔 / 4)) * a ^ 3) / (q - 1) ^ 6`, where `𝕔 = 100`.
The Challenge instead writes the value `2 ^ (443 * a ^ 3) / (q - 1) ^ 6` in `ℝ≥0∞`, as the
blueprint does. The lemma `coe_C1_0_2` below shows that the two agree when `q > 1`.

This file was generated by Claude Opus 5.5, using the other files in this project as input.
-/

public noncomputable section

open MeasureTheory Set ENNReal
open scoped NNReal

/-- For `q > 1`, the constant `C1_0_2 a q` of the metric space Carleson theorems equals
`2 ^ (443 * a ^ 3) / (q - 1) ^ 6`, the value used in the blueprint and in `PalomarChallenge`. -/
private lemma coe_C1_0_2 {a : ℕ} {q : ℝ≥0} (hq : q ∈ Ioc 1 2) :
    (C1_0_2 a q : ℝ≥0∞) = 2 ^ (443 * a ^ 3) / (q - 1) ^ 6 := by
  simp only [C1_0_2, 𝕔, Nat.reduceMul, Nat.reduceAdd, Nat.reduceDiv]
  rw [ENNReal.coe_div]
  · rfl
  · simpa [tsub_eq_zero_iff_le] using hq.1

section Statements

open Real Filter Topology

/-- **Carleson's theorem** (Theorem 1.0.1 in the blueprint): the partial Fourier sums of a
continuous `2π`-periodic function `f : ℝ → ℂ` converge to `f` almost everywhere. -/
theorem classical_carleson_theorem {f : ℝ → ℂ} (cont_f : Continuous f)
    (periodic_f : f.Periodic (2 * π)) :
    ∀ᵐ x, Tendsto (partialFourierSum · f x) atTop (𝓝 (f x)) :=
  classical_carleson cont_f periodic_f

/-- **Metric space Carleson theorem** (Theorem 1.1.1 in the blueprint): let `X` be a doubling
metric measure space, `Θ X` a cancellative compatible collection of functions and `K` a one-sided
Calderón–Zygmund kernel, all with parameter `a ≥ 4` (`KernelProofData a K`). Assume that the
nontangential operator `T_*` has `L²` operator norm at most `2 ^ (a ^ 3)` on bounded functions
with finite measure support. Then for `1 < q ≤ 2` with Hölder conjugate `q'`, for all
measurable `F, G ⊆ X` and all measurable `f` with `|f| ≤ 𝟙_F`, the generalized Carleson operator
`T` satisfies the restricted weak type estimate
`∫_G T f ≤ 2 ^ (443 a³) / (q - 1) ^ 6 · μ(G) ^ (1 / q') · μ(F) ^ (1 / q)`. -/
theorem metric_space_carleson {X : Type*} {a : ℕ} [MetricSpace X] {q q' : ℝ≥0} {F G : Set X}
    {K : X → X → ℂ} [KernelProofData a K] {f : X → ℂ} [IsCancellative X (defaultτ a)]
    (hq : q ∈ Ioc 1 2) (hqq' : q.HolderConjugate q') (mF : MeasurableSet F) (mG : MeasurableSet G)
    (mf : Measurable f) (nf : (‖f ·‖) ≤ F.indicator 1)
    (hT : HasBoundedStrongType (nontangentialOperator K · ·) 2 2 volume volume (C_Ts a)) :
    ∫⁻ x in G, carlesonOperator K f x ≤
      (2 ^ (443 * a ^ 3) / (q - 1) ^ 6 : ℝ≥0∞) * volume G ^ (q' : ℝ)⁻¹ * volume F ^ (q : ℝ)⁻¹ := by
  rw [← coe_C1_0_2 hq]
  exact metric_carleson hq hqq' mF mG mf nf hT

/-- **Linearized metric space Carleson theorem** (Theorem 1.1.2 in the blueprint): the same
setting as `metric_space_carleson`, now with a measurable function `Q : X → Θ X` with finite
range. Assume that for every `θ ∈ Θ X` the operator `T_Q^θ` has `L²` operator norm at most
`2 ^ (a ^ 3)` on bounded functions with finite measure support. Then the linearized Carleson
operator `T_Q` satisfies
`∫_G T_Q f ≤ 2 ^ (443 a³) / (q - 1) ^ 6 · μ(G) ^ (1 / q') · μ(F) ^ (1 / q)`. -/
theorem linearized_metric_space_carleson {X : Type*} {a : ℕ} [MetricSpace X] {q q' : ℝ≥0}
    {F G : Set X} {K : X → X → ℂ} [KernelProofData a K] {Q : SimpleFunc X (Θ X)} {f : X → ℂ}
    [IsCancellative X (defaultτ a)]
    (hq : q ∈ Ioc 1 2) (hqq' : q.HolderConjugate q') (mF : MeasurableSet F) (mG : MeasurableSet G)
    (mf : Measurable f) (nf : (‖f ·‖) ≤ F.indicator 1)
    (hT : ∀ θ : Θ X, HasBoundedStrongType (linearizedNontangentialOperator Q θ K · ·)
      2 2 volume volume (C_Ts a)) :
    ∫⁻ x in G, linearizedCarlesonOperator Q K f x ≤
      (2 ^ (443 * a ^ 3) / (q - 1) ^ 6 : ℝ≥0∞) * volume G ^ (q' : ℝ)⁻¹ * volume F ^ (q : ℝ)⁻¹ := by
  rw [← coe_C1_0_2 hq]
  exact linearized_metric_carleson hq hqq' mF mG mf nf hT

end Statements
