module

public import Mathlib.Analysis.Fourier.AddCircle

/-!
# Carleson's theorem and Carleson operators on doubling metric measure spaces

This is the Challenge file (the statement file a reader should audit) for the Carleson
formalization project <https://github.com/fpvandoorn/carleson>. It imports only Mathlib. The
definitions below are verbatim copies of the ones in `Carleson/Defs.lean` of the project (only
the documentation has been expanded), so they are the exact definitions the proofs use.
`PalomarSolution.lean` proves the three theorems at the end of this file.

The mathematical source is the blueprint
*A blueprint for the formalization of Carleson's theorem on convergence of Fourier series*
by L. Becker, M. I. de Frutos-Fernández, L. Diedering, F. van Doorn, S. Gouëzel, A. Jamneshan,
E. Karunus, E. van de Meent, P. Monticone, J. Mulder-Sohn, J. Portegies, J. Roos, M. Rothgang,
R. Srivastava, J. Sundstrom, J. Tan and C. Thiele
(<https://florisvandoorn.com/carleson/blueprint/>). The metric space theorems are from
L. Becker, F. van Doorn, A. Jamneshan, R. Srivastava and C. Thiele,
*Carleson operators on doubling metric measure spaces* (arXiv:2405.06423). Theorem and equation
numbers below refer to the blueprint.

This file was generated by Claude Opus 5.5, using the other files in this project as input.

## The three theorems

* `classical_carleson_theorem` (Theorem 1.0.1): Carleson's theorem (L. Carleson,
  *On convergence and growth of partial sums of Fourier series*, Acta Math. 116 (1966)). If
  `f : ℝ → ℂ` is continuous and `2π`-periodic, then for Lebesgue-almost every `x : ℝ` the partial
  Fourier sums `S_N f x = ∑_{n = -N}^{N} f̂ₙ e^{inx}` converge to `f x` as `N → ∞`. Here
  `f̂ₙ = (2π)⁻¹ ∫_0^{2π} f(y) e^{-iny} dy` (`partialFourierSum`, which uses Mathlib's
  `fourierCoeffOn` and `fourier`). We only prove this for continuous functions. Carleson's
  theorem for `L²` functions and Hunt's extension to `Lᵖ`, `p > 1`, are *not* part of this
  statement.

* `metric_space_carleson` (Theorem 1.1.1, the main theorem of arXiv:2405.06423): a restricted
  weak type estimate for a generalized Carleson operator on a doubling metric measure space.
  Take a natural number `a ≥ 4` and `1 < q ≤ 2` with Hölder conjugate `q'`. Let `X` be a doubling
  metric measure space with doubling constant `2 ^ a`, let `Θ X` be a cancellative compatible
  collection of real-valued continuous functions on `X`, and let `K` be a one-sided
  Calderón–Zygmund kernel. Assume that the maximally truncated nontangential singular integral
  `T_*` of `K` is bounded on `L²` with norm at most `2 ^ (a ^ 3)` (tested on bounded functions
  with finite measure support). Then for all measurable sets `F, G ⊆ X` and every measurable
  `f : X → ℂ` with `|f| ≤ 𝟙_F`,
  `∫_G T f dμ ≤ 2 ^ (443 a³) / (q - 1) ^ 6 · μ(G) ^ (1 / q') · μ(F) ^ (1 / q)`,
  where
  `T f x = sup_{θ ∈ Θ X} sup_{0 < R₁ < R₂} |∫_{R₁ < dist x y < R₂} K x y f y e^{i θ(y)} dμ(y)|`
  is the generalized Carleson operator (`carlesonOperator`).

* `linearized_metric_space_carleson` (Theorem 1.1.2): the same estimate for the linearized
  operator `T_Q f x = sup_{0 < R₁ < R₂} |∫_{R₁ < dist x y < R₂} K x y f y e^{i Q(x)(y)} dμ(y)|`
  (`linearizedCarlesonOperator`), where `Q : X → Θ X` is measurable with finite range (a
  `SimpleFunc`). Here `L²`-boundedness of `T_*` is replaced by the weaker assumption that for
  every `θ` the operator `T_Q^θ` (`linearizedNontangentialOperator`) is bounded on `L²`. In
  `T_Q^θ` the outer truncation radius at `x'` is capped by
  `R_Q(θ, x') = sup {r > 0 | d_{B(x', r)}(θ, Q x') < 1}` (`upperRadius`).

In the project the classical theorem is derived from the metric one. The proof of Theorem 1.0.1
applies Theorem 1.1.1 (through a two-sided variant) to `X = ℝ` with Lebesgue measure, `a = 4`,
the functions `y ↦ n * y` (`n ∈ ℤ`) as `Θ` and a Hilbert-type kernel. This shows that the
hypotheses of the metric theorems can be satisfied. The proofs only use the standard axioms
`propext`, `Classical.choice` and `Quot.sound`.

## The definitions

* `MeasureTheory.DoublingMeasure X A`: `X` is complete and locally compact, and carries a Borel
  measure `volume` that is locally finite, nonzero and doubling:
  `μ(B(x, 2r)) ≤ A μ(B(x, r))` for all `x` and `r` ((1.1.2) in the blueprint). With `A = 2 ^ a`
  this is the blueprint's "doubling metric measure space `(X, ρ, μ, a)`".
* `FunctionDistances 𝕜 X`: a type `Θ X` with an injective map into `C(X, 𝕜)` (so we may think of
  `Θ X` as a set of continuous functions), and for every center `x` and radius `r` a
  pseudometric `dist_{x, r}` on `Θ X`. This plays the role of the blueprint's metric `d_B` for
  `B = B(x, r)`.
* `CompatibleFunctions ℝ X A`: the compatibility axioms (1.1.4)–(1.1.8) of the blueprint.
  There is a point `o` where all `θ ∈ Θ X` vanish. The local oscillation on `B(x, r)` is bounded
  by `dist_{x, r}`. The distances are monotone in the ball. There are the two doubling-type
  inequalities `d_{B(x₂, 2r)} ≤ A · d_{B(x₁, r)}` if `x₁ ∈ B(x₂, 2r)`, and
  `2 d_{B(x₁, r)} ≤ d_{B(x₂, A r)}` if `B(x₁, r) ⊆ B(x₂, A r)`. Finally, every
  `dist_{x, r}`-ball of radius `2R` is covered by `A` balls of radius `R`.
* `IsCancellative X τ`: the cancellation (van der Corput type) condition (1.1.9):
  `|∫ e^{i(θ(y) - ϑ(y))} φ(y) dμ(y)| ≤ A μ(B) ‖φ‖_{Lip(B)} (1 + d_B(θ, ϑ)) ^ (-τ)` for every
  ball `B = B(x, r)` with `r > 0` and every `φ : X → ℂ` supported in `B`. Here `‖φ‖_{Lip(B)}` is
  the inhomogeneous Lipschitz norm `iLipENorm`. It is used with `τ = 1 / a` (`defaultτ`).
* `IsOneSidedKernel a K`: `K : X → X → ℂ` is measurable, `|K x y| ≤ 2 ^ (a³) / V(x, y)` and
  `|K x y - K x y'| ≤ (ρ(y, y') / ρ(x, y)) ^ (1 / a) · 2 ^ (a³) / V(x, y)` whenever
  `2 ρ(y, y') ≤ ρ(x, y)`. Here `V(x, y) = μ(B(x, ρ(x, y)))` (`Real.vol`).
* `KernelProofData a K` bundles `DoublingMeasure X (2 ^ a)`, `4 ≤ a`,
  `CompatibleFunctions ℝ X (2 ^ a)` and `IsOneSidedKernel a K`.
* `nontangentialOperator` is the operator `T_*` ((1.1.13) in the blueprint):
  `T_* f x = sup_{0 < R₁ < R₂} sup_{x' ∈ B(x, R₁)} |∫_{R₁ < ρ(x', y) < R₂} K x' y f y dμ(y)|`.
* `HasBoundedStrongType T 2 2 μ μ c`: for every `g` that is essentially bounded with support
  of finite measure (`BoundedFiniteSupport`), `T g` is a.e. strongly measurable and
  `‖T g‖_{L²} ≤ c ‖g‖_{L²}`. It is used with `c = 2 ^ (a³)` (`C_Ts`).

The operators take values in `ℝ≥0∞`, the conclusion is a lower Lebesgue integral `∫⁻`, and
`μ(G) ^ (1 / q')` is the blueprint's `μ(G) ^ (1 - 1 / q)`. The integrals inside the operators are
Bochner integrals, which Mathlib sets to `0` for non-integrable functions. Under the hypotheses
of the theorems this never happens for the integrals in the conclusion: on the annulus
`R₁ < ρ(x, y) < R₂` with `R₁ > 0` we have `|K x y| ≤ 2 ^ (a³) / μ(B(x, R₁))`, the annulus has
finite measure and `f` is bounded and measurable.

## Differences from the blueprint

These are formal details. Only the third one makes a hypothesis formally stronger than in the
blueprint.
* The distances `dist_{x, r}` on `Θ X` are indexed by pairs `(x, r)` instead of by balls, they
  are only required to be pseudometrics, and the axioms are also imposed for radii `r ≤ 0`.
  A compatible collection in the sense of the blueprint gives one in this sense: take the
  blueprint's `d_{B(x, r)}` for `r > 0` and set `dist_{x, r} = 0` for `r ≤ 0`.
* The size bound on `K` is required for all `x, y`, including `x = y`. This forces `K x x = 0`.
  Changing `K` on the diagonal does not change any of the operators, since `y = x` never lies in
  the annuli we integrate over.
* In `IsCancellative`, the test functions `φ` are those supported in `B` with finite Lipschitz
  norm *on `B`*. Such a `φ` need not be continuous on `X` (e.g. `φ = 𝟙_B`). So the formal
  hypothesis is at least as strong as the blueprint's condition, which is for Lipschitz
  `φ : X → ℂ` supported in `B`. The formal hypothesis holds in the classical case `X = ℝ`, as
  the project proves.
* In the `L²` hypothesis the test functions are essentially bounded (not bounded) with support
  of finite measure. Since `T_* g` only depends on the a.e. class of `g`, this is equivalent to
  the blueprint's condition. The hypothesis also asks that `T_* g` be a.e. strongly measurable,
  which is implicit in the blueprint when it writes the `L²` norm of `T_* g`.
* In the project the constant of Theorems 1.1.1 and 1.1.2 is `C1_0_2 a q`. It is defined in terms
  of a parameter `𝕔 = 100` (the blueprint takes `D = 2 ^ (100 a²)`) and equals
  `2 ^ (443 a³) / (q - 1) ^ 6`. Here we write this value explicitly, which is how the blueprint
  states the theorems. `PalomarSolution.lean` does the conversion.
-/

@[expose] public noncomputable section

open MeasureTheory Measure Metric Complex Set ENNReal
open scoped NNReal

open Real in
/-- The `N`-th partial Fourier sum of `f : ℝ → ℂ`, viewed as a `2π`-periodic function:
`S_N f x = ∑_{n = -N}^{N} f̂ₙ e^{inx}`, where `f̂ₙ = (2π)⁻¹ ∫_0^{2π} f(y) e^{-iny} dy` is the `n`-th
Fourier coefficient of `f` on the interval `[0, 2π]`. -/
def partialFourierSum (N : ℕ) (f : ℝ → ℂ) (x : ℝ) : ℂ := ∑ n ∈ Finset.Icc (-(N : ℤ)) N,
    fourierCoeffOn Real.two_pi_pos f n * fourier n (x : AddCircle (2 * π))

/- Basic definitions not specific to this project. -/
section BasicDefinitions

variable {X E : Type*}

/-- The "volume function" `V(x, y) = μ(B(x, ρ(x, y)))`, the (real-valued) measure of the ball
centered at `x` with `y` on its boundary. -/
protected def Real.vol [PseudoMetricSpace X] [MeasureSpace X] (x y : X) : ℝ :=
  volume.real (ball x (dist x y))

/-- The open annulus `{y | r < dist x y < R}` centered at `x`, with real radii. -/
def Set.Annulus.oo [PseudoMetricSpace X] (x : X) (r R : ℝ) := {y | dist x y ∈ Ioo r R}

/-- The open annulus `{y | r < edist x y < R}` centered at `x`, with radii in `ℝ≥0∞`. -/
def Set.EAnnulus.oo [PseudoMetricSpace X] (x : X) (r R : ℝ≥0∞) := {y | edist x y ∈ Ioo r R}

/-- The inhomogeneous Lipschitz norm of `φ` on the ball `B(x₀, R)`:
`sup_{x ∈ B} |φ x| + R · sup_{x, y ∈ B, x ≠ y} |φ x - φ y| / ρ(x, y)`, with values in `ℝ≥0∞`. -/
def iLipENorm {𝕜 X : Type*} [NormedField 𝕜] [PseudoMetricSpace X]
  (φ : X → 𝕜) (x₀ : X) (R : ℝ) : ℝ≥0∞ :=
  (⨆ x ∈ ball x₀ R, ‖φ x‖ₑ) +
  ENNReal.ofReal R * ⨆ (x ∈ ball x₀ R) (y ∈ ball x₀ R) (_ : x ≠ y), ‖φ x - φ y‖ₑ / edist x y

variable {𝕜 X : Type*} {A : ℕ} [_root_.RCLike 𝕜] [PseudoMetricSpace X] in
/-- The local oscillation of two functions `f, g` on a set `E`:
`sup_{z₁, z₂ ∈ E} |f z₁ - g z₁ - f z₂ + g z₂|`. For `E` a ball this is the left-hand side of
(1.1.4) in the blueprint. -/
def localOscillation (E : Set X) (f g : C(X, 𝕜)) : ℝ≥0∞ :=
  ⨆ z ∈ E ×ˢ E, ENNReal.ofReal ‖f z.1 - g z.1 - f z.2 + g z.2‖

variable {X E : Type*} [MeasurableSpace X] {f g : X → E}
  {μ : Measure X} [TopologicalSpace E] [ENorm E] [Zero E] in
/-- `f` is essentially bounded (it lies in `L^∞(μ)`, in particular it is a.e. strongly
measurable) and its support has finite measure. -/
@[fun_prop]
structure BoundedFiniteSupport (f : X → E) (μ : Measure X := by volume_tac) : Prop where
  /-- `f` lies in `L^∞(μ)`. -/
  memLp_top : MemLp f ∞ μ
  /-- The support of `f` has finite measure. -/
  measure_support_lt : μ (Function.support f) < ∞

/-- `T` has bounded strong type `(p, p')` with constant `c`: for every `f` in `L^∞` with support
of finite measure (`BoundedFiniteSupport`), `T f` is a.e. strongly measurable and
`‖T f‖_{L^{p'}(ν)} ≤ c ‖f‖_{Lᵖ(μ)}`. This is Mathlib's `HasStrongType` restricted to such `f`. -/
def MeasureTheory.HasBoundedStrongType
    {ε₁ ε₂ : Type*} [ENorm ε₁] [ENorm ε₂] [TopologicalSpace ε₁] [TopologicalSpace ε₂] [Zero ε₁]
    {α α' : Type*} {_x : MeasurableSpace α} {_x' : MeasurableSpace α'}
    (T : (α → ε₁) → (α' → ε₂))
    (p p' : ℝ≥0∞) (μ : Measure α) (ν : Measure α') (c : ℝ≥0∞) : Prop :=
  ∀ f : α → ε₁, BoundedFiniteSupport f μ →
    AEStronglyMeasurable (T f) ν ∧ eLpNorm (T f) p' ν ≤ c * eLpNorm f p μ

/-- A doubling measure is a measure on a metric space such that doubling the radius of a ball
increases its measure by at most the factor `A`, independent of the ball. -/
class MeasureTheory.Measure.IsDoubling {X : Type*} [MeasurableSpace X] [PseudoMetricSpace X]
    (μ : Measure X) (A : outParam ℝ≥0) : Prop where
  /-- The doubling condition `μ(B(x, 2r)) ≤ A μ(B(x, r))`. -/
  measure_ball_two_le_same : ∀ (x : X) r, μ (ball x (2 * r)) ≤ A * μ (ball x r)
export IsDoubling (measure_ball_two_le_same)

/-- A doubling metric measure space: `X` is complete and locally compact, and carries a
nonzero, locally finite Borel measure `volume` that is doubling with constant `A`.
This is the blueprint's "doubling metric measure space `(X, ρ, μ, a)`" for `A = 2 ^ a`. -/
class MeasureTheory.DoublingMeasure (X : Type*) (A : outParam ℝ≥0) [PseudoMetricSpace X] extends
    CompleteSpace X, LocallyCompactSpace X,
    MeasureSpace X, BorelSpace X,
    IsLocallyFiniteMeasure (volume : Measure X),
    Measure.IsDoubling (volume : Measure X) A, NeZero (volume : Measure X) where

end BasicDefinitions

/- Definitions specific to Carleson's theorem. -/
section setup

universe u

/-- A type `Θ X` with an injective map into the continuous functions `C(X, 𝕜)`, together with a
pseudometric on `Θ X` for every ball, that is, for every center `x : X` and radius `r : ℝ`.
Using a separate type is convenient for indexing these functions. -/
class FunctionDistances (𝕜 : outParam Type*) (X : Type u) [NormedField 𝕜] [TopologicalSpace X] where
  /-- A type of continuous functions from `X` to `𝕜`. -/
  Θ : Type u
  /-- The coercion map from `Θ` to `C(X, 𝕜)`. -/
  coeΘ : Θ → C(X, 𝕜)
  /-- Injectivity of the coercion map from `Θ` to `C(X, 𝕜)`. -/
  coeΘ_injective {f g : Θ} (h : ∀ x, coeΘ f x = coeΘ g x) : f = g
  /-- For each `_x : X` and `_r : ℝ`, a `PseudoMetricSpace Θ`. -/
  metric : ∀ (_x : X) (_r : ℝ), PseudoMetricSpace Θ

export FunctionDistances (Θ coeΘ)

section FunctionDistances

variable {𝕜 X : Type*} {A : ℕ} [_root_.RCLike 𝕜] [PseudoMetricSpace X] [d : FunctionDistances 𝕜 X]

/-- An element of `Θ X` is a continuous function on `X`. -/
instance : Coe (Θ X) C(X, 𝕜) := ⟨FunctionDistances.coeΘ⟩
/-- Elements of `Θ X` can be applied to points of `X`. -/
instance : FunLike (Θ X) X 𝕜 where
  coe := fun f ↦ (f : C(X, 𝕜))
  coe_injective _ _ hfg := FunctionDistances.coeΘ_injective fun x ↦ congrFun hfg x

set_option linter.unusedVariables false in
/-- A copy of `Θ X` that carries the pseudometric `dist_{x, r}` associated to the ball
`B(x, r)`. -/
@[nolint unusedArguments]
def WithFunctionDistance (x : X) (r : ℝ) := Θ X

/-- The pseudometric on `Θ X` associated to the ball `B(x, r)`. -/
instance {x : X} {r : ℝ} : PseudoMetricSpace (WithFunctionDistance x r) := d.metric x r

end FunctionDistances

/-- The real-valued distance function on `WithFunctionDistance x r`, i.e. the distance `d_B` on
`Θ X` associated to the ball `B = B(x, r)`. -/
notation3 "dist_{" x ", " r "}" => @dist (WithFunctionDistance x r) _
/-- The `ℝ≥0∞`-valued distance function on `WithFunctionDistance x r`. -/
notation3 "edist_{" x ", " r "}" => @edist (WithFunctionDistance x r) _

variable {𝕜 X : Type*} {A : ℕ} [_root_.RCLike 𝕜] [PseudoMetricSpace X]

set_option linter.unusedVariables false in
/-- `s` can be covered by at most `n` balls with radius `r`. -/
@[mk_iff]
class inductive CoveredByBalls (s : Set X) (n : ℕ) (r : ℝ) : Prop where
  /-- `s` is covered by the balls of radius `r` centered at the (at most `n`) points of
  `balls`. -/
  | mk (balls : Finset X)
    (card_balls : balls.card ≤ n)
    (union_balls : s ⊆ ⋃ x ∈ balls, ball x r) : CoveredByBalls s n r

variable (X) in
/-- Every ball of radius `r` in `X` is covered by `n` balls of radius `r'`. -/
def BallsCoverBalls (r r' : ℝ) (n : ℕ) : Prop := ∀ x : X, CoveredByBalls (ball x r) n r'

variable (X) in
/-- For all `r`, every ball of radius `a * r` in `X` is covered by `n` balls of radius `r`. -/
def AllBallsCoverBalls (a : ℝ) (n : ℕ) : Prop := ∀ r : ℝ, BallsCoverBalls X (a * r) r n

/-- A compatible collection of functions (Section 1.1 of the blueprint): the functions in `Θ X`
and the pseudometrics `dist_{x, r}` satisfy conditions (1.1.4)–(1.1.8) of the blueprint.
`A` will be `2 ^ a`. -/
class CompatibleFunctions (𝕜 : outParam Type*) (X : Type u) (A : outParam ℕ)
  [RCLike 𝕜] [PseudoMetricSpace X] extends FunctionDistances 𝕜 X where
  /-- There is a point `o` at which all functions in `Θ X` vanish. -/
  eq_zero : ∃ o : X, ∀ f : Θ, coeΘ f o = 0
  /-- The distance is bounded below by the local oscillation. (1.1.4) -/
  localOscillation_le_cdist {x : X} {r : ℝ} {f g : Θ} :
    localOscillation (ball x r) (coeΘ f) (coeΘ g) ≤ ENNReal.ofReal (dist_{x, r} f g)
  /-- The distance is monotone in the ball. (1.1.6) -/
  cdist_mono {x₁ x₂ : X} {r₁ r₂ : ℝ} {f g : Θ}
    (h : ball x₁ r₁ ⊆ ball x₂ r₂) : dist_{x₁, r₁} f g ≤ dist_{x₂, r₂} f g
  /-- The distance of a ball with large radius is bounded above. (1.1.5) -/
  cdist_le {x₁ x₂ : X} {r : ℝ} {f g : Θ} (h : dist x₁ x₂ < 2 * r) :
    dist_{x₂, 2 * r} f g ≤ A * dist_{x₁, r} f g
  /-- The distance of a ball with large radius is bounded below. (1.1.7) -/
  le_cdist {x₁ x₂ : X} {r : ℝ} {f g : Θ} (h1 : ball x₁ r ⊆ ball x₂ (A * r)) :
    /-(h2 : A * r ≤ Metric.diam (univ : Set X))-/
    2 * dist_{x₁, r} f g ≤ dist_{x₂, A * r} f g
  /-- Every ball of radius `2R` can be covered by `A` balls of radius `R`. (1.1.8) -/
  allBallsCoverBalls {x : X} {r : ℝ} :
    AllBallsCoverBalls (WithFunctionDistance x r) 2 A

variable [DoublingMeasure X A]

variable (X) in
/-- The compatible collection `Θ X` is `τ`-cancellative (condition (1.1.9) in the blueprint,
where `τ = 1 / a`). -/
class IsCancellative (τ : ℝ) [CompatibleFunctions ℝ X A] : Prop where
  /-- For every ball `B = B(x, r)` with `r > 0`, every `φ : X → ℂ` supported in `B` with finite
  inhomogeneous Lipschitz norm on `B`, and all `f, g ∈ Θ X`:
  `|∫ e^{i(f(y) - g(y))} φ(y) dμ(y)| ≤ A μ(B) ‖φ‖_{Lip(B)} (1 + d_B(f, g)) ^ (-τ)`. -/
  enorm_integral_exp_le' {x : X} {r : ℝ} {φ : X → ℂ} (hr : 0 < r) (h1 : iLipENorm φ x r ≠ ∞)
    (h2 : Function.support φ ⊆ ball x r) {f g : Θ X} :
    ‖∫ x, exp (I * (f x - g x)) * φ x‖ₑ ≤
    (A : ℝ≥0∞) * volume (ball x r) * iLipENorm φ x r * (1 + edist_{x, r} f g) ^ (- τ)

/-- `R_Q(θ, x) = sup {r > 0 | d_{B(x, r)}(θ, Q x) < 1}`, defined in (1.1.17) of the blueprint.
Radii `r ≤ 0` contribute `0` to the supremum, so they do not matter. -/
def upperRadius [FunctionDistances ℝ X] (Q : X → Θ X) (θ : Θ X) (x : X) : ℝ≥0∞ :=
  ⨆ (r : ℝ) (_ : dist_{x, r} θ (Q x) < 1), ENNReal.ofReal r

/-- The linearized maximally truncated nontangential Calderón–Zygmund operator `T_Q^θ`:
`T_Q^θ f x = sup_{0 < R₁ < R₂} sup_{x' ∈ B(x, R₁)} |∫_E K x' y f y dμ(y)|`, where `E` is the
annulus `R₁ < ρ(x', y) < min(R₂, R_Q(θ, x'))` ((1.1.18) in the blueprint). -/
def linearizedNontangentialOperator [FunctionDistances ℝ X] (Q : X → Θ X) (θ : Θ X)
    (K : X → X → ℂ) (f : X → ℂ) (x : X) : ℝ≥0∞ :=
  ⨆ (R₂ : ℝ) (R₁ ∈ Ioo 0 R₂) (x' ∈ ball x R₁),
  ‖∫ y in EAnnulus.oo x' (ENNReal.ofReal R₁) (min (ENNReal.ofReal R₂) (upperRadius Q θ x')),
    K x' y * f y‖ₑ

/-- The maximally truncated nontangential Calderón–Zygmund operator `T_*`:
`T_* f x = sup_{0 < R₁ < R₂} sup_{x' ∈ B(x, R₁)} |∫_{R₁ < ρ(x', y) < R₂} K x' y f y dμ(y)|`. -/
def nontangentialOperator (K : X → X → ℂ) (f : X → ℂ) (x : X) : ℝ≥0∞ :=
  ⨆ (R₂ : ℝ) (R₁ ∈ Ioo 0 R₂) (x' ∈ ball x R₁), ‖∫ y in Annulus.oo x' R₁ R₂, K x' y * f y‖ₑ

/-- The integrand in the (linearized) Carleson operator:
`∫_{R₁ < ρ(x, y) < R₂} K x y f y e^{i θ(y)} dμ(y)`. -/
def carlesonOperatorIntegrand [FunctionDistances ℝ X] (K : X → X → ℂ)
    (θ : Θ X) (R₁ R₂ : ℝ) (f : X → ℂ) (x : X) : ℂ :=
  ∫ y in Annulus.oo x R₁ R₂, K x y * f y * exp (I * θ y)

/-- The linearized generalized Carleson operator `T_Q`, with values in `ℝ≥0∞`:
`T_Q f x = sup_{0 < R₁ < R₂} |∫_{R₁ < ρ(x, y) < R₂} K x y f y e^{i Q(x)(y)} dμ(y)|`. -/
def linearizedCarlesonOperator [FunctionDistances ℝ X] (Q : X → Θ X) (K : X → X → ℂ)
    (f : X → ℂ) (x : X) : ℝ≥0∞ :=
  ⨆ (R₁ : ℝ) (R₂ : ℝ) (_ : 0 < R₁) (_ : R₁ < R₂), ‖carlesonOperatorIntegrand K (Q x) R₁ R₂ f x‖ₑ

/-- The generalized Carleson operator `T`, with values in `ℝ≥0∞`:
`T f x = sup_{θ ∈ Θ X} sup_{0 < R₁ < R₂} |∫_{R₁ < ρ(x, y) < R₂} K x y f y e^{i θ(y)} dμ(y)|`. -/
def carlesonOperator [FunctionDistances ℝ X] (K : X → X → ℂ) (f : X → ℂ) (x : X) : ℝ≥0∞ :=
  ⨆ (θ : Θ X), linearizedCarlesonOperator (fun _ ↦ θ) K f x

end setup

/-- The doubling constant `2 ^ a`, used as the argument `A` of `DoublingMeasure` and
`CompatibleFunctions`. -/
@[simp] abbrev defaultA (a : ℕ) : ℕ := 2 ^ a
/-- The cancellation exponent `τ = 1 / a`. -/
@[simp] def defaultτ (a : ℕ) : ℝ := a⁻¹

section Kernel

variable {X : Type*} {a : ℕ} {K : X → X → ℂ} [PseudoMetricSpace X] [MeasureSpace X]
open Function

/-- The constant `2 ^ (a ^ 3)` used twice in the definition of a Calderón–Zygmund kernel. -/
@[simp] def C_K (a : ℝ) : ℝ≥0 := 2 ^ a ^ 3

/-- `K` is a one-sided Calderón–Zygmund kernel (conditions (1.1.10)–(1.1.12) of the blueprint).
Here `K x y` is defined everywhere, also for `x = y`. The size bound then forces `K x x = 0`. -/
class IsOneSidedKernel (a : outParam ℕ) (K : X → X → ℂ) : Prop where
  /-- `K` is measurable as a function on `X × X`. -/
  measurable_K : Measurable (uncurry K)
  /-- The size condition `|K x y| ≤ 2 ^ (a³) / V(x, y)`. -/
  norm_K_le_vol_inv (x y : X) : ‖K x y‖ ≤ C_K a / Real.vol x y
  /-- The smoothness condition in the second variable: if `2 ρ(y, y') ≤ ρ(x, y)` then
  `|K x y - K x y'| ≤ (ρ(y, y') / ρ(x, y)) ^ (1 / a) · 2 ^ (a³) / V(x, y)`. -/
  norm_K_sub_le {x y y' : X} (h : 2 * dist y y' ≤ dist x y) :
    ‖K x y - K x y'‖ ≤ (dist y y' / dist x y) ^ (a : ℝ)⁻¹ * (C_K a / Real.vol x y)

end Kernel

/-- The setting of the metric space Carleson theorems: `X` is a doubling metric measure space
with constant `2 ^ a`, `a ≥ 4`, `Θ X` is a compatible collection of functions (with constant
`2 ^ a`) and `K` is a one-sided Calderón–Zygmund kernel. -/
class KernelProofData {X : Type*} (a : outParam ℕ) (K : outParam (X → X → ℂ))
    [PseudoMetricSpace X] where
  /-- `X` is a doubling metric measure space with constant `2 ^ a`. -/
  d : DoublingMeasure X (defaultA a)
  /-- The parameter `a` is at least `4`. -/
  four_le_a : 4 ≤ a
  /-- `Θ X` is a compatible collection of functions with constant `2 ^ a`. -/
  cf : CompatibleFunctions ℝ X (defaultA a)
  /-- `K` is a one-sided Calderón–Zygmund kernel. -/
  hcz : IsOneSidedKernel a K

export KernelProofData (four_le_a)

attribute [implicit_reducible, instance] KernelProofData.d KernelProofData.cf

attribute [instance] KernelProofData.hcz

set_option linter.unusedVariables false

/-- The constant `2 ^ (a ^ 3)` bounding the `L²` operator norm of `T_*` and `T_Q^θ` in the
hypotheses of the metric space Carleson theorems. -/
def C_Ts (a : ℕ) : ℝ≥0 := 2 ^ a ^ 3

section Statements

open Real Filter Topology

/-- **Carleson's theorem** (Theorem 1.0.1 in the blueprint): the partial Fourier sums of a
continuous `2π`-periodic function `f : ℝ → ℂ` converge to `f` almost everywhere. -/
theorem classical_carleson_theorem {f : ℝ → ℂ} (cont_f : Continuous f)
    (periodic_f : f.Periodic (2 * π)) :
    ∀ᵐ x, Tendsto (partialFourierSum · f x) atTop (𝓝 (f x)) :=
  sorry

/-- **Metric space Carleson theorem** (Theorem 1.1.1 in the blueprint): let `X` be a doubling
metric measure space, `Θ X` a cancellative compatible collection of functions and `K` a one-sided
Calderón–Zygmund kernel, all with parameter `a ≥ 4` (`KernelProofData a K`). Assume that the
nontangential operator `T_*` has `L²` operator norm at most `2 ^ (a ^ 3)` on bounded functions
with finite measure support. Then for `1 < q ≤ 2` with Hölder conjugate `q'`, for all
measurable `F, G ⊆ X` and all measurable `f` with `|f| ≤ 𝟙_F`, the generalized Carleson operator
`T` satisfies the restricted weak type estimate
`∫_G T f ≤ 2 ^ (443 a³) / (q - 1) ^ 6 · μ(G) ^ (1 / q') · μ(F) ^ (1 / q)`. -/
theorem metric_space_carleson {X : Type*} {a : ℕ} [MetricSpace X] {q q' : ℝ≥0} {F G : Set X}
    {K : X → X → ℂ} [KernelProofData a K] {f : X → ℂ} [IsCancellative X (defaultτ a)]
    (hq : q ∈ Ioc 1 2) (hqq' : q.HolderConjugate q') (mF : MeasurableSet F) (mG : MeasurableSet G)
    (mf : Measurable f) (nf : (‖f ·‖) ≤ F.indicator 1)
    (hT : HasBoundedStrongType (nontangentialOperator K · ·) 2 2 volume volume (C_Ts a)) :
    ∫⁻ x in G, carlesonOperator K f x ≤
      (2 ^ (443 * a ^ 3) / (q - 1) ^ 6 : ℝ≥0∞) * volume G ^ (q' : ℝ)⁻¹ * volume F ^ (q : ℝ)⁻¹ :=
  sorry

/-- **Linearized metric space Carleson theorem** (Theorem 1.1.2 in the blueprint): the same
setting as `metric_space_carleson`, now with a measurable function `Q : X → Θ X` with finite
range. Assume that for every `θ ∈ Θ X` the operator `T_Q^θ` has `L²` operator norm at most
`2 ^ (a ^ 3)` on bounded functions with finite measure support. Then the linearized Carleson
operator `T_Q` satisfies
`∫_G T_Q f ≤ 2 ^ (443 a³) / (q - 1) ^ 6 · μ(G) ^ (1 / q') · μ(F) ^ (1 / q)`. -/
theorem linearized_metric_space_carleson {X : Type*} {a : ℕ} [MetricSpace X] {q q' : ℝ≥0}
    {F G : Set X} {K : X → X → ℂ} [KernelProofData a K] {Q : SimpleFunc X (Θ X)} {f : X → ℂ}
    [IsCancellative X (defaultτ a)]
    (hq : q ∈ Ioc 1 2) (hqq' : q.HolderConjugate q') (mF : MeasurableSet F) (mG : MeasurableSet G)
    (mf : Measurable f) (nf : (‖f ·‖) ≤ F.indicator 1)
    (hT : ∀ θ : Θ X, HasBoundedStrongType (linearizedNontangentialOperator Q θ K · ·)
      2 2 volume volume (C_Ts a)) :
    ∫⁻ x in G, linearizedCarlesonOperator Q K f x ≤
      (2 ^ (443 * a ^ 3) / (q - 1) ^ 6 : ℝ≥0∞) * volume G ^ (q' : ℝ)⁻¹ * volume F ^ (q : ℝ)⁻¹ :=
  sorry

end Statements
