# 1 = pdflatex
$pdf_mode = 1;

# Define the xelatex command (if we want to move back to minted)
$xelatex = 'xelatex -shell-escape -interaction=nonstopmode -file-line-error -synctex=1 %O %S';

# Default file to compile if no file is specified in the terminal
@default_files = ('main.tex');

$bibtex = 'biber';