on:
  pull_request:

jobs:
  style_lint:
    name: Lint style
    runs-on: ubuntu-latest
    steps:
      - name: Don't 'import Mathlib', use precise imports
        if: always()
        run: |
          ! (find Carleson -name "*.lean" -type f -print0 | xargs -0 grep -E -n '^import Mathlib$')

  build_project:
    runs-on: ubuntu-latest
    name: Build project
    steps:
      - name: Checkout project
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Configure Lean
        uses: leanprover/lean-action@38fbc41a8c28c4cbaec22d7f7de508ec2e7c0dd9 # 2025-07-02
        with:
          auto-config: false
          use-github-cache: false
          use-mathlib-cache: true
          lake-package-directory: tools # Building here

      - name: check that Carleson.lean is up to date
        run: ~/.elan/bin/lake exe mk_all --check --lib Carleson

      - name: Build and lint project
        uses: leanprover/lean-action@38fbc41a8c28c4cbaec22d7f7de508ec2e7c0dd9 # 2025-07-02
        with:
          build: true
          lint: true
          mk_all-check: false # would need to pass '--lib Carleson' to mk_all to enable

      - name: Build comparator challenge and solution files
        run: ~/.elan/bin/lake build Challenge Solution

      - name: Generate the paper PDF
        uses: xu-cheng/texlive-action@22c04326a5d855880f9d39bb955138bf11c6df80 # v3
        with:
          docker_image: ghcr.io/xu-cheng/texlive-full:20251002
          run: |
            cd paper
            latexmk main.tex
            latexmk -c

      - name: Compile blueprint and documentation
        uses: leanprover-community/docgen-action@3dbd3475a9bc8d22fd786a8f8efe1869457da7cc # 2026-01-15
        with:
          blueprint: true
          homepage: docs