on:
  pull_request:

jobs:
  style_lint:
    name: Lint style
    runs-on: ubuntu-latest
    steps:
      - name: Don't 'import Mathlib', use precise imports
        if: always()
        run: |
          ! (find Carleson -name "*.lean" -type f -print0 | xargs -0 grep -E -n '^import Mathlib$')

  build_project:
    runs-on: ubuntu-latest
    name: Build project
    steps:
      - name: Checkout project
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Build and lint project
        uses: leanprover/lean-action@v1
        env:
          LEAN_ABORT_ON_PANIC: "1"
        with:
          build: true
          build-args: "Carleson Challenge Solution"
          lint: true
          mk_all-check: true
          mk_all-args: "--lib Carleson"

      - name: Generate the paper PDF
        uses: xu-cheng/texlive-action@22c04326a5d855880f9d39bb955138bf11c6df80 # v3
        with:
          docker_image: ghcr.io/xu-cheng/texlive-full:20251002
          run: |
            cd paper
            latexmk main.tex
            latexmk -c

      - name: Compile blueprint and documentation
        uses: leanprover-community/docgen-action@3dbd3475a9bc8d22fd786a8f8efe1869457da7cc # 2026-01-15
        with:
          blueprint: true
          homepage: docs
